spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ""
    port: 0
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000 # one day

    register:
      token:
        expiration-in-minutes: 15
        characters-token: 0123456789
        token-length: 6

    mailing:
      frontend:
        activation-url:
          http://localhost:4200/activation-account
  file:
    upload:
      photos-output-path: ./uploads

  cors:
    urls: http://localhost:4200
    allowed-methods: POST,GET,PATCH,DELETE,OPTIONS
    allowed-headers: Origin,Content-Type,Accept,Authorization

server:
  port: 8088